### ISSUE TITLE
Tablet resources smoke test

### ISSUE THREAD

**Issue by mtarcha** [CrazyCouple/TActive#8]
- Test tablet will be able to host services (Nuget, CI, Symbol Server)

**DOD**
- wiki page

**Comment by iivchenko** [comment]
# TODO
- [x] Find micro SD 
- [x] Check for viruses with DR.WEB
- [x] Create users
  - [x] For Slava
   - [x] For Me
   - [x] For Server Admin
- [x] Configure
   - [x] RDP
   - [x] Firewall for RDP
- [x] Minimize resource consumption
   - [x] Stop unnecessary services and apps
   - [x] Uninstall unnecessary apps, updates, roles etc.
- [x] Install serves
  - [x] Jenkins
  - [x] Nuget
  - [x] Symbol
  - [x] Source
- [ ] Defrag

**Comment by iivchenko** [comment]
# Links to investigate
* [Article about creating Nuget server with own feeds](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview)
* [TeamCity as a Symbol Server and Source Server](https://confluence.jetbrains.com/display/TW/Symbol+Server)
* [Symbol server over IIS and file share](https://www.jamf.com/jamf-nation/articles/309/using-iis-to-enable-http-downloads-on-a-windows-server-2008-or-2012-file-share-distribution-point) as good as for Nuget packages server I think!
* [IIS and symstore](https://msdn.microsoft.com/en-us/library/windows/hardware/ff549781(v=vs.85).aspx)
* [Source Server and Symbol Server Support in TFS 2010](http://www.edsquared.com/2011/02/12/Source+Server+And+Symbol+Server+Support+In+TFS+2010.aspx)
* [An interesting source indexing project](https://github.com/ctaggart/SourceLink)
* [Code Project about Symbol server](https://www.codeproject.com/Articles/115125/Source-Indexing-and-Symbol-Servers-A-Guide-to-Easi)
* [Symbol server setup](http://brockreeve.com/post/2009/10/23/Symbol-Server-Setup.aspx)
* [Hosting your own Source & Symbol Server](https://blog.jayway.com/2011/06/19/hosting-your-own-source-symbol-server/)
* [SymStore](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681417(v=vs.85).aspx)
* [Symbol server GitHub](https://gist.github.com/baldurk/c6feb31b0305125c6d1a)
* Indexing tools
  * [PDBGIT](https://github.com/AArnott/PdbGit)
  * [GitTools](https://github.com/GitTools)
* [NetFoundation and there is a symstore repo](https://github.com/dotnet)
* [Deploy Site to IIS](https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/deploying-to-iis)

**Comment by iivchenko** [comment]
[TeamCity as a Symbol Server and Source Server](https://confluence.jetbrains.com/display/TW/Symbol+Server)

**Comment by iivchenko** [comment]
[Symbol server over IIS and file share](https://www.jamf.com/jamf-nation/articles/309/using-iis-to-enable-http-downloads-on-a-windows-server-2008-or-2012-file-share-distribution-point)

**Comment by iivchenko** [comment]
. A native C++ PDB file contains quite a bit of information:

Public, private, and static function addresses
Global variable names and addresses
Parameter and local variable names and offsets where to find them on the stack
Type data consisting of class, structure, and data definitions
Frame Pointer Omission (FPO) data, which is the key to native stack walking on x86
Source file names and their lines
A .NET PDB only contains two pieces of information, the source file names and their lines and the local variable names. All the other information is already in the .NET metadata so there is no need to duplicate the same information in a PDB file.

When you load a module into the process address space, the debugger uses two pieces of information to find the matching PDB file. The first is obviously the name of the file. If you load ZZZ.DLL, the debugger looks for ZZZ.PDB. The extremely important part is how the debugger knows this is the exact matching PDB file for this binary. That’s done through a GUID that’s embedded in both the PDB file and the binary. If the GUID does not match, you certainly won’t debug the module at the source code level.

The .NET compiler, and for native the linker, puts this GUID into the binary and PDB. Since the act of compiling creates this GUID, stop and think about this for a moment. If you have yesterday’s build and did not save the PDB file will you ever be able to debug the binary again? No! This is why it is so critical to save your PDB files for every build. Because I know you’re thinking it, I’ll go ahead and answer the question already forming in your mind: no, there’s no way to change the GUID.

**Comment by iivchenko** [comment]
.\nuget pack .\TestPackage.csproj -properties Configuration=Release -OutputDirectory .\bin
.\nuget.exe push .\bin\TestPackage.1.0.0.nupkg -Source http://azjol-nerub:81/api/v2/package

& "C:\Program Files\Windows Kits\10\Debuggers\x86\symstore.exe" add /f .\TestPackage.pdb /s D:\SymStore\ /t "TestPackage" /v 1.0.0.0

pdbgit .\TestPackage.pdb -u https://raw.githubusercontent.com/CrazyCouple/Prototypes

**Comment by iivchenko** [comment]
# Brief workflow

* Build binaries
* Create and push package
* pdbgit for pdbs
* push to symstore
* configure VS and resharper
